title: Serena Chen | Portfolio
email: serenadantingchen@gmail.com
description: > 
  Serena Chen is a product designer based in Wellington. She loves great typography, math, and geeking out over security.
baseurl: "" 
url: ""
twitter_username: Sereeena
github_username: heisenburger

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed